{ config, lib, pkgs, ... }:

with lib;

let
  cfg = config.local.editors.emacs;
  c = config.local.theme."rose-pine-slate".colors;

  # Merged env: nixpkgs aspell only finds dicts via $NIX_PROFILES, which
  # GUI Emacs doesn't inherit, so we point ASPELL_CONF at this path instead.
  aspellWithEn = pkgs.symlinkJoin {
    name = "aspell-with-en-dict";
    paths = [ pkgs.aspell pkgs.aspellDicts.en ];
  };
in
{
  options.local.editors.emacs = {
    enable = mkOption {
      type = types.bool;
      default = false;
    };
  };

  config = mkIf cfg.enable {
    programs.emacs = {
      enable = true;
      package = pkgs.emacs;

      extraPackages = epkgs: with epkgs; [
        evil
        evil-collection
        evil-surround
        evil-commentary

        auctex
        cdlatex
        pdf-tools

        doom-modeline
        nerd-icons
        nerd-icons-dired
        nerd-icons-completion

        vertico
        marginalia
        orderless
        consult

        dashboard
        magit
        rainbow-delimiters

        sly

      ];

      extraConfig = ''
        ;;; Nix paths (GUI Emacs doesn't inherit a shell PATH) ;;;
        (let ((per-user-bin "/etc/profiles/per-user/${config.home.username}/bin")
              (system-bin "/run/current-system/sw/bin"))
          (setenv "PATH" (concat per-user-bin path-separator
                                  system-bin path-separator
                                  (or (getenv "PATH") "")))
          (setq exec-path (append (list per-user-bin system-bin) exec-path)))

        ;;; Evil ;;;
        (setq evil-want-integration t)
        (setq evil-want-keybinding nil)
        (setq evil-want-C-u-scroll t)
        (setq evil-want-Y-yank-to-eol t)
        (require 'evil)

        (with-eval-after-load 'evil
          (when (require 'evil-collection nil t)
            (evil-collection-init))
          (require 'evil-surround)
          (global-evil-surround-mode 1)
          (require 'evil-commentary)
          (evil-commentary-mode 1))

        ;; Flyspell owns C-. (auto-correct); evil-repeat-pop is not worth it.
        (define-key evil-normal-state-map (kbd "C-.") nil)

        (evil-mode 1)

        ;;; Look & feel ;;;
        (setq inhibit-startup-screen t
              visible-bell t
              use-dialog-box nil
              frame-title-format "%b")

        (tool-bar-mode -1)
        (menu-bar-mode -1)
        (scroll-bar-mode -1)

        (add-to-list 'default-frame-alist '(font . "Hasklig-12"))

        (global-hl-line-mode 1)
        (show-paren-mode 1)
        (column-number-mode 1)
        (pixel-scroll-precision-mode 1)
        (which-key-mode 1)

        ;; Matches rose-pine-slate used across the rest of the setup;
        ;; generated from the shared nix palette (see core/rose-pine-slate.nix)
        (deftheme rose-pine-slate "Rose Pine Slate, generated by home-manager")
        (custom-theme-set-faces
         'rose-pine-slate
         `(default ((t (:background "${c.base}" :foreground "${c.text}"))))
         `(cursor ((t (:background "${c.rose}"))))
         `(fringe ((t (:background "${c.base}"))))
         `(region ((t (:background "${c.overlay}"))))
         `(highlight ((t (:background "${c.overlay}"))))
         `(hl-line ((t (:background "${c.surface}"))))
         `(vertical-border ((t (:foreground "${c.overlay}"))))
         `(minibuffer-prompt ((t (:foreground "${c.foam}"))))
         `(mode-line ((t (:background "${c.surface}" :foreground "${c.subtle}"))))
         `(mode-line-inactive ((t (:background "${c.base}" :foreground "${c.muted}"))))
         `(line-number ((t (:foreground "${c.overlay}"))))
         `(line-number-current-line ((t (:foreground "${c.subtle}"))))
         `(show-paren-match ((t (:background "${c.overlay}" :foreground "${c.rose}" :weight bold))))
         `(isearch ((t (:background "${c.gold}" :foreground "${c.base}"))))
         `(lazy-highlight ((t (:background "${c.overlay}" :foreground "${c.text}"))))
         `(error ((t (:foreground "${c.love}"))))
         `(warning ((t (:foreground "${c.gold}"))))
         `(success ((t (:foreground "${c.foam}"))))
         `(font-lock-comment-face ((t (:foreground "${c.muted}" :slant italic))))
         `(font-lock-string-face ((t (:foreground "${c.gold}"))))
         `(font-lock-keyword-face ((t (:foreground "${c.pine}"))))
         `(font-lock-builtin-face ((t (:foreground "${c.love}"))))
         `(font-lock-function-name-face ((t (:foreground "${c.rose}"))))
         `(font-lock-variable-name-face ((t (:foreground "${c.iris}"))))
         `(font-lock-type-face ((t (:foreground "${c.foam}"))))
         `(font-lock-constant-face ((t (:foreground "${c.gold}"))))
         `(rainbow-delimiters-depth-1-face ((t (:foreground "${c.rose}"))))
         `(rainbow-delimiters-depth-2-face ((t (:foreground "${c.iris}"))))
         `(rainbow-delimiters-depth-3-face ((t (:foreground "${c.foam}"))))
         `(rainbow-delimiters-depth-4-face ((t (:foreground "${c.gold}"))))
         `(rainbow-delimiters-depth-5-face ((t (:foreground "${c.love}"))))
         `(rainbow-delimiters-depth-6-face ((t (:foreground "${c.pine}")))))
        (enable-theme 'rose-pine-slate)

        (setq-default display-line-numbers-type 'relative)
        (add-hook 'prog-mode-hook #'display-line-numbers-mode)
        (add-hook 'prog-mode-hook #'rainbow-delimiters-mode)

        ;;; Modeline & icons ;;;
        (require 'doom-modeline)
        (setq doom-modeline-height 25
              doom-modeline-buffer-file-name-style 'relative-to-project)
        (doom-modeline-mode 1)

        (require 'nerd-icons)
        (add-hook 'dired-mode-hook #'nerd-icons-dired-mode)
        (nerd-icons-completion-mode 1)
        (add-hook 'marginalia-mode-hook #'nerd-icons-completion-marginalia-setup)

        ;;; Minibuffer completion ;;;
        (setq completion-styles '(orderless basic)
              completion-category-overrides '((file (styles basic partial-completion))))
        (require 'vertico)
        (setq vertico-cycle t)
        (vertico-mode 1)
        (marginalia-mode 1)
        (keymap-global-set "C-x b" #'consult-buffer)
         (keymap-global-set "M-g i" #'consult-imenu)
        (keymap-global-set "C-x g" #'magit-status)

        ;;; Startup dashboard ;;;

        (require 'dashboard)
        (dashboard-setup-startup-hook)
        (setq dashboard-center-content t
              dashboard-startup-banner 'logo)

        ;;; Flyspell/aspell ;;;
        ;; Dicts live outside aspell's own store path; see aspellWithEn above.
        (setenv "ASPELL_CONF" "dict-dir ${aspellWithEn}/lib/aspell")

        ;;; LaTeX LSP (texlab via built-in eglot) ;;;
        (add-hook 'LaTeX-mode-hook #'eglot-ensure)

        ;;; LaTeX (AUCTeX) ;;;
        (with-eval-after-load 'tex
          (setq TeX-auto-save t
                TeX-parse-self t
                TeX-PDF-mode t
                TeX-view-program-selection '((output-pdf "PDF Tools"))
                TeX-source-correlate-method '((dvi . source-specials)
                                              (pdf . synctex))
                TeX-source-correlate-start-server t)
          (TeX-source-correlate-mode t)
          (add-hook 'TeX-after-compilation-finished-functions
                    #'TeX-revert-document-buffer)
          (defun local/TeX-compile-on-save ()
            (TeX-command "LaTeX" 'TeX-master-file))
          (add-hook 'LaTeX-mode-hook
                    (lambda ()
                      (add-hook 'after-save-hook #'local/TeX-compile-on-save nil t))))

        (require 'pdf-tools)
        (require 'pdf-info)
        (setq pdf-info-epdfinfo-program
              (expand-file-name "epdfinfo"
                                (file-name-directory (locate-library "pdf-tools"))))
        (pdf-tools-install-noverify)
        (with-eval-after-load 'latex
          (define-key LaTeX-mode-map (kbd "C-c C-g")
                      #'pdf-sync-forward-search))

        ;;; preview-latex ;;;

        (add-hook 'LaTeX-mode-hook 'LaTeX-preview-setup)
        (setq preview-image-type 'png)
        ;; NOTE: keep the default "auctex" pass-option — prauctex.def is
        ;; what emits the "Preview: Snippet N" markers AUCTeX parses.
        ;; Removing it silently disables all previews.

        ;; GS >= 10 forces -dSAFER, which blocks preview's PostScript
        ;; from re-opening the source PDF (/invalidfileaccess).
        ;; -dDELAYSAFER (the old default) no longer disables it.
        (setq preview-gs-options '("-q" "-dNOSAFER" "-dNOPAUSE"
                                   "-DNOPLATFONTS" "-dPrinted"
                                   "-dTextAlphaBits=4"
                                   "-dGraphicsAlphaBits=4"))

         (add-hook 'LaTeX-mode-hook 'LaTeX-math-mode)
         (add-hook 'LaTeX-mode-hook 'turn-on-reftex)
         (add-hook 'LaTeX-mode-hook #'flyspell-mode)
         (add-hook 'LaTeX-mode-hook #'display-line-numbers-mode)
         (setq reftex-plug-into-AUCTeX t)

        ;;; Common Lisp (SLY) ;;;
        ;; Absolute store path: GUI Emacs may not inherit a shell PATH.
        (setq inferior-lisp-program "${pkgs.sbcl}/bin/sbcl")
       '';
     };

     home.packages = [
       pkgs.texlab
       pkgs.ghostscript
       pkgs.sbcl
       aspellWithEn
     ];

  };
}
